import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import Loader from "../../components/Loader";
import { HodlContext } from "../../store/hodl";
import PrimaryCardStyle from "../../components/PrimaryCardStyle";
const Collectors = () => {
    const holdContext = useContext(HodlContext);
    if (holdContext.collectors.length === 0) return <Loader />;
    return (
        <div className="collectors mt-10 mb-20">
            <Head>
                <title>KW | Hodls</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                <h1 className="text-3xl font-bold tracking-wider">
                    <span className="text-pink">KW</span> Collectors
                </h1>
                <hr className=" my-5" style={{ borderColor: "rgb(226 232 240)" }} />
                <div className="grid gap-8 grid-cols-3 lg:grid-cols-3 sm:grid-cols-2 xs:grid-cols-1 mt-6 px-4">
                    {holdContext.collectors
                        .filter((v, i, a) => a.findIndex((v2) => v2._id === v._id) === i)
                        .map((r, i) => (
                            <div key={r._id}>
                                <PrimaryCardStyle
                                    media={`https://paras-cdn.imgix.net/${r.imgUrl.replace("ipfs://", "")}`}
                                    cover={r.coverUrl !== undefined ? r.coverUrl.replace("ipfs://", "") : r.imgUrl.replace("ipfs://", "")}
                                    title={r.accountId}
                                />
                            </div>
                            // <p key={r._id}>{r.accountId}</p>
                        ))}
                </div>
            </div>
        </div>
    );
};

export default Collectors;
