import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { parasApi } from "../../../api";
import CollectionCard from "../../../components/CollectionCard";
import Loader from "../../../components/Loader";

const Collection = () => {
    const [collections, setCollections] = useState([]);
    const [isLoading, setLoading] = useState(false);
    const router = useRouter();
    const { slug } = router.query;
    const capitalize = (str) => {
        return str.charAt(0).toUpperCase() + str.slice(1);
    };
    useEffect(() => {
        if (slug === "paras") {
            setTimeout(() => {
                parasApi
                    .get("collections?creator_id=kamwoo.near")
                    .then((r) => {
                        setCollections((collection) => [...collection, r.data.data.results]);
                    })
                    .catch((err) => console.log(err));
            }, 1000);
        }
    }, [slug]);
    if (collections.length === 0) return <Loader />;
    return (
        <div className="collections mt-10 mb-20">
            <Head>
                <title>KW | {capitalize(slug)} Marketplace</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                <div>
                    <h1 className="text-3xl font-bold tracking-wider">Collections</h1>
                    <hr className=" my-5" style={{ borderColor: "rgb(226 232 240)" }} />
                    <div className="grid gap-8 grid-cols-3 mt-6 ">
                        {collections[0]
                            .sort((a, b) => (a.createdAt < b.createdAt ? -1 : 1))
                            .map((r, i) => (
                                <Link href={`/gallery/marketplace/collection/${r.collection_id}`} key={r._id}>
                                    <a>
                                        <CollectionCard media={`https://paras-cdn.imgix.net/${r.media}`} cover={r.cover === undefined ? null : r.cover} title={r.collection} />
                                    </a>
                                </Link>
                            ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Collection;
