import Head from "next/head";
import { useEffect, useState } from "react";
import CollectionCard from "../../components/CollectionCard";
import Hero from "../../components/Hero";
import { collections } from "../../db";
import Loader from "../../components/Loader";
const Collections = () => {
    const [isLoading, setLoading] = useState(false);
    useEffect(() => {
        setTimeout(() => {
            setLoading(true);
        }, 1500);
    }, []);
    if (!isLoading) return <Loader />;
    return (
        <div className="collections mb-20">
            <Head>
                <title>KW | Collection</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                <Hero />
                <hr className="w-1/2 mx-auto my-10" style={{ borderColor: "rgb(226 232 240)" }} />
                <div>
                    <h1 className="text-3xl font-bold tracking-wider">Marketplace</h1>
                    <div className="grid gap-8 grid-cols-3 mt-6 ">
                        {collections.map((r, i) => (
                            <CollectionCard values={r} key={r._id} />
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Collections;
