import Head from "next/head";
import CollectionCard from "../components/CollectionCard";
import Hero from "../components/Hero";
import { collections } from "../db";
const Collections = () => {
    return (
        <div className="collections">
            <Head>
                <title>KW | Collection</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                <Hero />
                <hr className="w-1/2 mx-auto my-10" style={{ borderColor: "rgb(226 232 240)" }} />
                <div>
                    <h1 className="text-3xl font-sans font-bold tracking-wider">Collections</h1>
                    <div className="grid gap-8 grid-cols-3 mt-6 ">
                        {collections.map((r, i) => (
                            <CollectionCard values={r} key={r._id} />
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Collections;
