import Head from "next/head";
import Card from "../components/Card";
import Hero from "../components/Hero";
import { news } from "../db";
export default function Home() {
    return (
        <div className="landing-page">
            <Head>
                <title>KW</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                <Hero />
                <div className="mt-20">
                    <h1 className="text-3xl font-sans font-bold tracking-wider">News</h1>
                    <div className="grid gap-10 grid-cols-4 grid-rows-2 mt-6 ">
                        {news.map((r, i) => (
                            <Card values={r} key={r._id} />
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}
