import Head from "next/head";
import { useEffect, useState } from "react";
import { parasApi } from "../api";
import Card from "../components/Card";
import Hero from "../components/Hero";
import Stats from "../components/Stats";
import { news } from "../db";

export default function Home() {
    const [newRelease, setNewRelease] = useState([]);
    useEffect(() => {
        parasApi
            .get("token?__limit=4&creator_id=kamwoo.near")
            .then((r) => setNewRelease((token) => [...token, r.data.data.results]))
            .catch((err) => console.log(err));
    }, []);
    return (
        <div className="landing-page">
            <Head>
                <title>KW</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {newRelease.length !== 0 && (
                <div className="wrapper">
                    <Hero />
                    <hr className="w-1/2 mx-auto my-10" style={{ borderColor: "rgb(226 232 240)" }} />
                    <div>
                        <h1 className="text-3xl font-sans font-bold tracking-wider">News</h1>
                        <div className="grid gap-8 grid-cols-4 mt-6 ">
                            {news.map((r, i) => (
                                <div key={r._id}>
                                    <div>
                                        <Card media={r.media.image.link} />
                                        <div className="px-6 ">
                                            <h3 className="text-md font-medium tracking-wider">{r.title}</h3>
                                            <p className="text-xs font-normal text-gray tracking-wide mt-1">{r.description}</p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <hr className="w-1/2 mx-auto my-10" style={{ borderColor: "rgb(226 232 240)" }} />
                    <Stats />
                    <hr className="w-1/2 mx-auto my-10" style={{ borderColor: "rgb(226 232 240)" }} />
                    <div>
                        <h1 className="text-3xl font-sans font-bold tracking-wider">New Releases</h1>
                        <div className="grid gap-8 grid-cols-4 mt-6 ">
                            {newRelease[0].map((r, i) => (
                                <div key={r._id}>
                                    <div>
                                        <Card media={`https://paras-cdn.imgix.net/${r.metadata.media}`} />
                                        <div className="px-6 text-center">
                                            <h3 className="text-md font-medium tracking-wider">{r.metadata.title}</h3>
                                            <p className="text-xs font-normal text-gray tracking-wide mt-1">{r.metadata.collection}</p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
