import Head from "next/head";
import Hero from "../components/Hero";
export default function Home() {
    return (
        <div className="landing-page">
            <Head>
                <title>KW</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <Hero />
            </div>
        </div>
    );
}
